### ISSUE TITLE
Indexes with spaces in names do not activate

### ISSUE THREAD

**Issue by aschegolskiy** [NeoZX/plume#6]
G:\>plume -u SYSDBA -p masterkey-t 3 -d localhost:database.fdb
Found 1357 indexes
Warning trouble on index **FK_IPC_QR_TRANSFER _1**

Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 32
-_1
I think if index name containing space symbol, doublequotes are necessary.
But thank to your program, I  found a buggy name in my DB

**Comment by NeoZX** [comment]
Fixed in v0.5.
