### ISSUE TITLE
Firebird restarts while index activating

### ISSUE THREAD

**Issue by aschegolskiy** [NeoZX/plume#8]
Hi, I tried to restore database without index activation, and then used plume.
But in process of activation indexes server hangs and restarts.
How can I find the reason of this issue?

**Comment by NeoZX** [comment]
What output plume?
What version of firebird?
You can check firebird.log. 
If server crashed check systems log.

**Comment by aschegolskiy** [comment]
I'll try to collect all info, and post it here.

**Comment by aschegolskiy** [comment]
I've got server crashes on HQBird 3.0.11.33622, Firebird 3.0.6.33328. Both x64 Win versions
[plume_output.txt](https://github.com/NeoZX/plume/files/9624006/plume_output.txt)
firebird.conf - used default configuration. I can provide it if necessary.
[server_log.txt](https://github.com/NeoZX/plume/files/9624025/server_log.txt)
[system.log](https://github.com/NeoZX/plume/files/9624114/system.log)

**Comment by NeoZX** [comment]
Looks like a bug in Firebird. 
Can you provide DB metadata and statiscs?
To extract metadata run gbak with key -m
gbak -user sysdba -pass masterkey -g -b -m localhost:datatabase metadata.gbk
or isql with key -x:
isql -user sysdba -pass masterkey -x localhost:datatabase >metadata.sql
Also need db statistics:
gstat -a -r -s -i -user sysdba -pass masterkey localhost:datatabase >gstat.txt

**Comment by aschegolskiy** [comment]
I've already opened the issue at firebird bugtracker.
https://github.com/FirebirdSQL/firebird/issues/7314
Sorry, I can't provide the metadata because of security reason. But I can provide statistics. Or without metadata it will be unnecessary?

**Comment by NeoZX** [comment]
Statistics will be helpful.
From the metadata, I want to understand how foreign keys relate to tables.
Only tables metadata (fields and dependencies) is needed. Triggers, stored procedures and etc not required.

**Comment by aschegolskiy** [comment]
I'll try to prepare the info. If you provide the email, I can send data to you.

**Comment by NeoZX** [comment]
send to *@*

**Comment by aschegolskiy** [comment]
I sent the requested info by email.
