### ISSUE TITLE
Execution Logs

### ISSUE THREAD

**Issue by aschegolskiy** [NeoZX/plume#9]
Can you please add ability to create execution log?
I'm especially interested in statistics like gbak parameters -st TD outputs:

> gbak: time     delta  
> gbak: 7349.095  0.003     activating and creating deferred index FSDATALOG_OBJ
> gbak: 7353.249  4.153     activating and creating deferred index FSDATALOG_TIME
> gbak: 7356.041  2.792     activating and creating deferred index PK_FSDATALOG
> gbak: 7358.901  2.859     activating and creating deferred index FSDATAKIND_CODE

It can help to analyze the changes in index restore time when the database grows.

**Comment by NeoZX** [comment]
I can add logging with timings.
But to analyze the growth of the database when restoring the index, fbtrace is more suitable.

You can start tracing with the command:
```
fbtracemgr -se service_mgr -user sysdba -pass masterkey -start -conf fbtrace.conf >fbtrace.log
```
with the following config file fbtrace.conf:
```
database
{
        enabled = true
        log_transactions = true
        log_statement_finish = true
        print_perf = true
        time_threshold = 0
}
```
In fbtrace.log you will see entries:
```
2022-10-09T13:28:38.1610 (3323:0x7f42ea860cc0) EXECUTE_STATEMENT_FINISH
        employee (ATT_104, SYSDBA:NONE, NONE, TCPv4:127.0.0.1/57374)
        /home/neozx/projects/plume/bin/plume:1485003
                (TRA_298, READ_COMMITTED | NO_REC_VERSION | WAIT | READ_WRITE)

-------------------------------------------------------------------------------
ALTER INDEX "SALESTATX" ACTIVE
...
2022-10-09T13:28:38.2600 (3323:0x7f42ea860cc0) COMMIT_TRANSACTION
        employee (ATT_104, SYSDBA:NONE, NONE, TCPv4:127.0.0.1/57374)
        /home/neozx/projects/plume/bin/plume:1485003
                (TRA_298, READ_COMMITTED | NO_REC_VERSION | WAIT | READ_WRITE)
     98 ms, 8 write(s), 111 fetch(es), 13 mark(s)
```
plume activates each index in a separate transaction. Therefore, the statistics at the commit will be only for one index. In the example above, the records are linked through **TRA_298** (transaction ID).

You can also collect a binary trace with subsequent infusion into the database, but it will be "offline".

**Comment by NeoZX** [comment]
tag:v0.5.2
